name: Code checking with Black

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - '**.py'

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4
          with:
            repository: ${{ github.event.pull_request.head.repo.full_name }}
            ref: ${{ github.event.pull_request.head.sha }}
            fetch-depth: 0

        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.12'

        - name: Install Black
          run: pip install black

        - name: Check code format with Black
          run: black --check .
